#!/usr/bin/env python3
"""Build the local Codex plugin bundle from the repo source tree."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import stat
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "plugins" / "switchboard"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Plugin bundle directory to create",
    )
    parser.add_argument(
        "--cachebuster",
        help="Cachebuster token for the Codex plugin version",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output = args.output.expanduser().resolve()
    if output == ROOT or ROOT in output.parents and output.relative_to(ROOT).parts[:1] == (".git",):
        raise SystemExit(f"Refusing unsafe output path: {output}")

    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)

    copy_tree(ROOT / ".codex-plugin", output / ".codex-plugin")
    copy_tree(ROOT / "switchboard", output / "switchboard")
    copy_tree(ROOT / "skills", output / "skills")
    copy_file(ROOT / "scripts" / "switchboard", output / "scripts" / "switchboard")
    copy_file(ROOT / "README.md", output / "README.md")

    version = update_manifest_version(
        output / ".codex-plugin" / "plugin.json",
        args.cachebuster or default_cachebuster(),
    )
    marker = {
        "generatedFrom": str(ROOT),
        "version": version,
        "note": "Generated by scripts/build_codex_plugin.py; do not edit this bundle.",
    }
    (output / ".generated.json").write_text(json.dumps(marker, indent=2) + "\n", encoding="utf-8")
    print(f"Built Codex plugin: {output}")
    print(f"Version: {version}")


def copy_tree(source: Path, destination: Path) -> None:
    shutil.copytree(
        source,
        destination,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )


def copy_file(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    if source.name == "switchboard":
        mode = destination.stat().st_mode
        destination.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def update_manifest_version(manifest_path: Path, cachebuster: str) -> str:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    base_version = str(manifest["version"]).split("+", 1)[0]
    version = f"{base_version}+codex.{sanitize_cachebuster(cachebuster)}"
    manifest["version"] = version
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return version


def sanitize_cachebuster(value: str) -> str:
    sanitized = re.sub(r"[^a-z0-9-]+", "-", value.strip().lower())
    sanitized = re.sub(r"-{2,}", "-", sanitized).strip("-")
    if not sanitized:
        raise SystemExit("Cachebuster must contain at least one letter or digit.")
    return sanitized


def default_cachebuster() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


if __name__ == "__main__":
    main()
